version: '3'
services:
  main:
    depends_on:
     - mysql
     - consul
     - registrator
     - redis
     - nginx
    labels:
      SERVICE_NAME: 'einvoice-send'
      SERVICE_TAGS: 'external'
      SERVICE_3007_CHECK_HTTP: '/api/health/check'
      SERVICE_3007_CHECK_INTERVAL: '15s'
      SERVICE_3007_CHECK_TIMEOUT: '3s'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_AUTH: ${REDIS_AUTH}
    ports:
     - '3007:3007'

  mysql:
    image: "mysql:5.6"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - registrator

  redis:
    image: opuscapita/redis:dev
    ports:
      - '6379:6379'
    environment:
      REDIS_AUTH: ${REDIS_AUTH}
    depends_on:
      - registrator
    labels:
      SERVICE_NAME: redis

  nginx:
    image: gr4per/nginx-rp:dev
    depends_on:
       - consul
    ports:
      - '8080:8080'
    depends_on:
      - consul

  registrator:
    image: gliderlabs/registrator
    command: consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul

  consul:
    image: consul:latest
    ports:
      - '8400:8400'
      - '8500:8500'
      - '8600:53/udp'
    labels:
      SERVICE_IGNORE: 'true'  # Do not add any of Consul's services to Consul's service discovery registry.
    command: [agent, '-server', '-ui', '-bootstrap', '-client=0.0.0.0']
